INSERT INTO algorithms (public_id, slug, name, category, difficulty, content) VALUES
('Ab3X9kPq', 'busca-binaria', 'Busca Binária', 'Busca', 'beginner', 
CONCAT('# Busca Binária', CHR(10), CHR(10),
'A **Busca Binária** é um algoritmo eficiente para encontrar um elemento em uma lista que já está **ordenada**.', CHR(10), CHR(10),
'## Como funciona?', CHR(10),
'1. Encontre o elemento do meio.', CHR(10),
'2. Se o valor for igual ao alvo, a busca termina.', CHR(10),
'3. Se for diferente, descarte a metade irrelevante.', CHR(10), CHR(10),
'### Exemplo em C++', CHR(10),
'```cpp', CHR(10),
'#include <iostream>', CHR(10),
'#include <vector>', CHR(10), CHR(10),
'int main() {', CHR(10),
'    std::vector<int> nums = {1, 3, 5, 7, 9, 11};', CHR(10),
'    std::cout << "Executando teste da Busca Binária..." << std::endl;', CHR(10),
'    return 0;', CHR(10),
'}', CHR(10),
'```', CHR(10), CHR(10),
'> **Complexidade de Tempo:** O(log n)')),

('F8mR2cQa', 'algoritmo-de-dijkstra', 'Algoritmo de Dijkstra', 'Grafos', 'intermediate', 
CONCAT('# Algoritmo de Dijkstra', CHR(10), CHR(10),
'O **Algoritmo de Dijkstra** resolve o problema do caminho mínimo em um grafo com pesos não negativos.', CHR(10), CHR(10),
'## Aplicações', CHR(10),
'* Sistemas de GPS e Mapas.', CHR(10),
'* Roteamento de pacotes na rede.', CHR(10), CHR(10),
'### Exemplo em C++', CHR(10),
'```cpp', CHR(10),
'#include <iostream>', CHR(10),
'#include <queue>', CHR(10), CHR(10),
'int main() {', CHR(10),
'    std::cout << "Inicializando grafo e executando Dijkstra..." << std::endl;', CHR(10),
'    return 0;', CHR(10),
'}', CHR(10),
'```', CHR(10), CHR(10),
'> **Nota:** Não suporta arestas com peso negativo.')),

('12345678', 'segment-tree', 'Segment Tree', 'Estrutura de Dados', 'advanced', 
CONCAT('# Segment Tree', CHR(10), CHR(10),
'A **Segment Tree** permite realizar consultas e atualizações em intervalos de um array de forma muito rápida.', CHR(10), CHR(10),
'## Operações', CHR(10),
'* **Point Update:** O(log n)', CHR(10),
'* **Range Query:** O(log n)', CHR(10), CHR(10),
'### Exemplo em C++', CHR(10),
'```cpp', CHR(10),
'#include <iostream>', CHR(10),
'#include <vector>', CHR(10), CHR(10),
'int main() {', CHR(10),
'    std::cout << "Construindo Segment Tree..." << std::endl;', CHR(10),
'    return 0;', CHR(10),
'}', CHR(10),
'```', CHR(10), CHR(10),
'> **Memória:** Requer aproximadamente 4n de espaço.')),

('1234abcd', 'heavy-light-decomposition', 'Heavy-Light Decomposition', 'Grafos', 'expert', 
CONCAT('# Heavy-Light Decomposition (HLD)', CHR(10), CHR(10),
'Técnica avançada usada para decompor árvores em cadeias de caminhos disjuntos.', CHR(10), CHR(10),
'## Aplicação', CHR(10),
'Permite responder a consultas de caminho entre nós em árvores usando uma **Segment Tree**.', CHR(10), CHR(10),
'### Exemplo em C++', CHR(10),
'```cpp', CHR(10),
'#include <iostream>', CHR(10), CHR(10),
'int main() {', CHR(10),
'    std::cout << "Decompondo árvore com HLD..." << std::endl;', CHR(10),
'    return 0;', CHR(10),
'}', CHR(10),
'```', CHR(10), CHR(10),
'> **Complexidade:** O(q log^2 n)'));