-- TABLES WITH FK
DROP TABLE IF EXISTS algorithms;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS user_social_accounts;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS users;

--TABLES WITHOUT FK
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;

-- TYPES
DROP TYPE IF EXISTS difficulty_level;
DROP TYPE IF EXISTS status_text;

--FUNCTIONS
DROP FUNCTION IF EXISTS update_updated_at;